[package]
name = "desktop-support"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
document-model = { path = "../document-model" }
editor-state = { path = "../editor-state" }
panel-workspace = { path = "../panel-workspace" }
serde.workspace = true
serde_json.workspace = true
tinyfiledialogs.workspace = true
