[package]
name = "altpaint-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[[bin]]
name = "altpaint"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
font8x8 = { workspace = true }
document-model = { path = "../../crates/document-model" }
editor-state = { path = "../../crates/editor-state" }
geometry = { path = "../../crates/geometry" }
raster = { path = "../../crates/raster" }
gpu-paint = { path = "../../crates/gpu-paint" }
paint-engine = { path = "../../crates/paint-engine" }
desktop-support = { path = "../../crates/desktop-support" }
panel-runtime = { path = "../../crates/panel-runtime" }
keyboard-types = "0.7"
pollster.workspace = true
canvas-geometry = { path = "../../crates/canvas-geometry" }
serde_json.workspace = true
storage = { path = "../../crates/storage" }
panel-workspace = { path = "../../crates/panel-workspace" }
wgpu.workspace = true
winit.workspace = true

[dev-dependencies]
