[package]
name = "paint-engine"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
app-core = { path = "../app-core" }
document-model = { path = "../document-model" }
editor-state = { path = "../editor-state" }
geometry = { path = "../geometry" }
raster = { path = "../raster" }
